### ISSUE TITLE
Does it support Robot framework command-line arguments

### ISSUE THREAD

**Issue by Sathish787** [rajeevnaikte/distbot#3]
In order to use this library, it has to support Robot Framework command-line arguments
include, -i
exclude, -e
--tagstatexclude
--suitestatlevel 

If already supports, let me know. Thanks

**Comment by rajeevnaikte** [comment]
Yes, it does. Some options are overridden, e.g. `-e` which is considered as ENV, but you can use `--exclude` for the RF command-line args.

Ref: [the usage section of the readme](https://github.com/rajeevnaikte/distbot#usage).

**Comment by Sathish787** [comment]
Thank you so much
